translations:
  en:
    contributor: "Contributor"
    role: "Role"
  es:
    contributor: "Contribuidor"
    role: "Rol"
    
# Roles are defined based on allcontributors emoji-key: https://allcontributors.org/
roles_map:
  code:                "💻"
  docs:                "📖"
  bug:                 "🐛"
  design:              "🎨"
  translation:         "🌍"
  data:                "🔣"
  tutorials:           "✅"
  ideas:               "🤔"
  projectManagement:   "📆"
  questions:           "💬"
  maintenance:         "🚧"
  tests:               "⚠️"
  userTesting:         "📓"
  infra:               "🚇"
  review:              "👀"
  

contributors:
  - name: "María Meraz"
    github: "mariameraz"
    roles: [code, projectManagement, questions, maintenance, infra, userTesting, tutorials, bug, docs, tests, ideas, translation, design]

  - name: "Héctor López"
    github: "hector-LM"
    roles: [docs, userTesting, tutorials, ideas, bug, data, translation]

  - name: "Juan Zalapa"
    roles: [data]
