translations:
  en:
    contributor: "Contributor"
    role: "Role"
  es:
    contributor: "Contribuidor"
    role: "Rol"

# Roles are defined based on allcontributors emoji-key: https://allcontributors.org/
roles_map:
  code: "💻" # Commits and PR
  docs: "📖" # Apport to Docs
  bug: "🐛" # Report bugs
  design: "🎨" # ui/ux
  translation: "🌍"
  data: "🔣" # contribuite data
  tutorials: "✅" # contribuite tutorials (add, update, suggestions..)
  ideas: "🤔" # feature proposals
  projectManagement: "📆" # plan and coordinate
  questions: "💬" # community support
  maintenance: "🚧" # refactoring
  tests: "⚠️" # create tests
  userTesting: "📓" # testing code
  infra: "🚇" # CI and hosting
  review: "👀" # reviewing PR

contributors:
  - name: "María Meraz"
    github: "mariameraz"
    roles:
      [
        code,
        maintenance,
        userTesting,
        tutorials,
        bug,
        docs,
        tests,
        questions,
        review,
        translation,
      ]

  - name: "Héctor López"
    github: "hector-LM"
    roles: [docs, userTesting, tutorials, ideas, bug, data, translation]

  - name: "Juan Zalapa"
    roles: [data]

  - name: "Álvaro Guerrero"
    github: "AlvaroGuerrero"
    roles: [bug]
