###############
# Metadata  ###
###############

site_name: Traitly
# site_url: https://mariameraz.github.io/traitly
site_description: Fruit phenotyping tool for morphological, structural, and color analysis
site_author: Maria Meraz
repo_name: mariameraz/traitly
repo_url: https://github.com/mariameraz/traitly

######################
# Theme configuration #
######################

theme:
  name: material
  icon:
    alternate: octicons/globe-24
    repo: fontawesome/brands/github-alt
    # view: material/eye

  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default # Light theme
      primary: black
      accent: blue gray # For headers, links, etc 
      toggle:
        icon: octicons/sun-24
        name: Switch to dark mode

    - scheme: slate # Dark theme
      primary: white
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky # Visible tabs while scrolling.
    - navigation.path # Shows the current page's path in the nav.
    - navigation.sections # Shows section headers in the nav as collapsible groups.
    - navigation.expand # Expand navegation tree
    - navigation.indexes
    - navigation.top # Adds a top bar at the bottom of the page 
    - navigation.footer
    
    - search.highlight
    - search.share
    - search.suggest

    - content.code.copy
    - content.code.select
    - content.code.annotate

    - toc.follow
    - toc.integrate


#######################
# Markdown extensions #
#######################

markdown_extensions:
  - admonition
  - pymdownx.details # to collapse admotions 
  - pymdownx.superfences
 
  - pymdownx.highlight:
      anchor_linenums: true

  - pymdownx.inlinehilite

  - pymdownx.tabbed:
      alternate_style: true
  
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - tables
  - attr_list # for markdowon atributes
  - md_in_html # for html  

  - toc:
      permalink: true


###########
# Plugins #
###########
plugins:
  - search
  # - mkdocs-jupyter:
  #     ignore_h1_titles: True

  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
          nav:
            - Home: en/index.md

            - Installation: en/installation.md

            - User Guide: 
                - Traitly Architecture: en/workflow/overview.md
                - Internal analysis: 
                  - Image Specifications: en/workflow/int_image_requirements.md
                  - Internal Analyzer Class: en/workflow/internal_class.md  
                - External analysis:
                  - Image Specifications: en/workflow/ext_image_requirements.md
                  - External Analyzer Class: en/workflow/external_class.md
                - CLI:
                  - Command Line Interface: en/workflow/cli.md
                - Results: 
                  - Overview: en/workflow/results/overview.md
                  - Measurements: en/workflow/results/measurements.md

            - Tutorials:
                - Overview: en/tutorials/overview.md
                - Quickstart: en/tutorials/quickstart.md
                - External Analysis: en/tutorials/external.md
                - Background Segmentation: en/tutorials/background_segmentation.md
                - Locule Segmentation: en/tutorials/segmentate_locules.md
                - Individual Analysis: en/tutorials/individual_img_tutorial_en.md
                - Batch Analysis: en/tutorials/batch_tutorial_en.md

            - API Reference:
                - Classes:
                    - FruitInternalAnalyzer: en/api/internal_analysis.md
                    - FruitExternalAnalyzer: en/api/external_analysis.md

                - Modules:
                    - mask: en/api/mask.md
                    - processing: en/api/processing.md
                    - color_analysis: en/api/color_analysis.md
                    - symmetry: en/api/symmetry.md
                    - color_plot: en/api/color_plot.md
                    - analysis_parameters: en/api/analysis_parameters.md
            
            - About: en/about.md
            - Changelog: en/changelog.md

        - locale: es
          name: Español
          build: true
          nav:
            - Home: es/index.md

            - Installation: es/installation.md

            - User Guide: 
                - Traitly Architecture: es/workflow/overview.md
                - Internal analysis: 
                  - Image Specifications: es/workflow/int_image_requirements.md
                  - Internal Analyzer Class: es/workflow/internal_class.md  
                - External analysis:
                  - Image Specifications: es/workflow/ext_image_requirements.md
                  - External Analyzer Class: es/workflow/external_class.md
                - CLI:
                  - Command Line Interface: es/workflow/cli.md
                - Results: 
                  - Overview: es/workflow/results/overview.md
                  - Measurements: es/workflow/results/measurements.md

            - Tutorials:
                - Overview: es/tutorials/overview.md
                - Quickstart: es/tutorials/quickstart.md
                - External Analysis: es/tutorials/external.md
                - Background Segmentation: es/tutorials/background_segmentation.md
                - Locule Segmentation: es/tutorials/segmentate_locules.md
                - Individual Analysis: es/tutorials/individual_img_tutorial_es.md
                - Batch Analysis: es/tutorials/batch_tutorial_es.md

            - API Reference:
                - Classes:
                    - FruitInternalAnalyzer: es/api/internal_analysis.md
                    - FruitExternalAnalyzer: es/api/external_analysis.md

                - Modules:
                    - mask: es/api/mask.md
                    - processing: es/api/processing.md
                    - color_analysis: es/api/color_analysis.md
                    - symmetry: es/api/symmetry.md
                    - color_plot: es/api/color_plot.md
                    - analysis_parameters: es/api/analysis_parameters.md
            
            - About: es/about.md
            - Changelog: es/changelog.md
            
          nav_translations:
            Home: Inicio
            Installation: Instalación
            User Guide: Guía de Uso
            Results: Resultados
            Measurements: Mediciones
            Tutorials: Tutoriales
            Overview: Descripción General
            Quickstart: Inicio Rápido
            Internal Analysis: Análisis Interno
            External Analysis: Análisis Externo
            API Reference: Referencia API
            Changelog: Historial de Cambios
            Image Specifications: Especificaciones de Imágenes
            Internal Analyzer Class: Clase de Analizador Interno
            External Analyzer Class: Clase de Analizador Externo
            Traitly Architecture: Arquitectura de Traitly
            Classes: Clases
            Modules: Módulos
            About: Acerca de
            Command Line Interface: Interfaz de Línea de Comandos
            Background Segmentation: Segmentación del Fondo
            Locule Segmentation: Segmentación de lóculos
            Individual Analysis: Análisis Individual
            Batch Analysis: Análisis por Lotes

  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: false
            show_root_heading: true
            show_category_heading: true
            members_order: source

  - git-committers:
      repository: mariameraz/traitly
      branch: main
      token: !ENV MKDOCS_GIT_COMMITTERS_APIKEY
      exclude:
        - en/index.md
        - es/index.md

  - git-revision-date-localized:
      type: date
      enable_creation_date: true
      locale: es
      exclude:
        - en/index.md
        - es/index.md

####################
# Navigation setup #
####################



#######################
# Extra configuration ##
#######################

copyright: Copyright &copy; 2026 Maria Alejandra Torres Meraz

extra:

  alternate:
    - name: English
      link: ""
      lang: en
    - name: Spanish
      link: es
      lang: es

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mariameraz/traitly
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alemeraz
    - icon: fontawesome/brands/python
      link: https://test.pypi.org/project/traitly/
    - icon: fontawesome/solid/envelope
      link: mailto:<ma.torresmeraz@gmail.com>

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - stylesheets/animations.js
