[build-system]
requires = ["hatchling>=1.26"]
build-backend = "hatchling.build"

[project]
name = "traitly"
version = "0.2.0"
description = "Computer vision toolkit for high-throughput fruit phenotyping."
readme = "README.md"
requires-python = ">=3.9"
license = { text = "AGPL-3.0-or-later" }
license-files = ["LICENSE*"]

authors = [
  {name = "Maria Alejandra Torres Meraz", email = "ma.torresmeraz@gmail.com"},
  {name = "Hector Lopez Moreno", email = "hectorlpzmno@gmail.com"}
]

dependencies = [
  "opencv-contrib-python==4.13.0.92",
  "opencv-python-headless==4.13.0.92",
  "numpy",
  "pandas",
  "scipy",
  "matplotlib",
  "tqdm",
  "psutil",
  "easyocr",
  "ultralytics",
  "rich-argparse",
  "ipython",
  "scikit-learn",
  "colour-science"
]



keywords = [
  "plant-phenotyping",
  "fruit-morphology",
  "plant-breeding"
]

classifiers = [
  "Development Status :: 4 - Beta",
  "Operating System :: OS Independent",
  "Environment :: Console",
  "Environment :: Web Environment",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Image Processing",
]

[project.optional-dependencies]
pdf = ["PyMuPDF"]
app = ["PyMuPDF", "shiny"]

dev = ["pytest", "pytest-cov"]

[project.scripts]
traitly = "traitly.cli:main"
traitly-app = "traitly.shiny_app.app:run"

[project.urls]
Repository = "https://github.com/mariameraz/traitly"
Documentation = "https://traitly.readthedocs.io/en/latest/"
Issues = "https://github.com/mariameraz/traitly/issues"
Changelog = "https://github.com/mariameraz/traitly/blob/main/CHANGELOG.md"
Demo = "https://huggingface.co/spaces/mariameraz/traitly"

[tool.hatch.build.targets.wheel]
packages = ["src/traitly"]

[tool.hatch.build]
include = [
    "src/traitly/**",
    "README.md",
    "LICENSE*"
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
source = ["src/traitly"]
