[build-system]
requires = ["hatchling>=1.26"]
build-backend = "hatchling.build"

[project]
name = "traitly"
version = "0.1.0"
description = "Open-source computer vision toolkit for high-throughput fruit phenotyping. Analyze fruit morphology (size, shape), internal anatomy (locule number, shape, size, symmetry), pericarp thickness, and extract tissue color metrics (RGB, LAB, HSV, grayscale)."
readme = "README.md"
requires-python = ">=3.9"
license = { text = "AGPL-3.0-or-later" }
license-files = ["LICENSE*"]

authors = [
  { name = "Maria Alejandra Torres Meraz", email = "ma.torresmeraz@gmail.com" },
  { name = "Hector Lopez Moreno", email = "hectorlpzmno@gmail.com" }
]

dependencies = [
  "opencv-contrib-python",
  "numpy",
  "pandas",
  "scipy",
  "matplotlib",
  "tqdm",
  "psutil",
  "easyocr",
  "ultralytics",
]


keywords = [
  "plant-phenotyping",
  "fruit-morphology",
  "crop-anatomy",
  "fruit-phenotyping",
  "locule-analysis",
  "locule-detection",
  "pericarp-thickness",
  "computer-vision",
  "agricultural-image-analysis",
  "plant-breeding-tools",
  "open-source-agriculture",
  "high-throughput-phenotyping"
]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Operating System :: OS Independent",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX :: Linux",
  "Operating System :: MacOS :: MacOS X",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12"
]

[project.optional-dependencies]
pdf = ["PyMuPDF"]
all = [
  "PyMuPDF", "shiny",
]
dev = ["pytest", "black", "isort", "flake8", "mypy"]

[project.scripts]
traitly = "traitly.cli:main"
traitly-app = "traitly.shiny_app.app:run"

[project.urls]
Repository = "https://github.com/mariameraz/traitly"
Source = "https://github.com/mariameraz/traitly/src"
Issues = "https://github.com/mariameraz/traitly/issues"
Discussion = "https://github.com/mariameraz/traitly/discussions"

[tool.hatch.build.targets.wheel]
packages = ["src/traitly"]

[tool.hatch.build]
include = [
  "src/traitly/**",
  "README.md",
  "LICENSE*",
]

[tool.hatch.build.targets.wheel.force-include]
"src/traitly/package_data/models" = "traitly/package_data/models"