[build-system]
requires = ["hatchling>=1.26"]
build-backend = "hatchling.build"

[project]
name = "traitly"
version = "0.1.1"
description = "Computer vision toolkit for high-throughput fruit phenotyping."
readme = "README.md"
requires-python = ">=3.9"
license = { text = "AGPL-3.0-or-later" }
license-files = ["LICENSE*"]

authors = [
  { name = "Maria Alejandra Torres Meraz", email = "ma.torresmeraz@gmail.com" },
  { name = "Hector Lopez Moreno", email = "hectorlpzmno@gmail.com" }
]

dependencies = [
  "opencv-contrib-python>=4.8,<5.0",
  "numpy>=1.24,<3.0",
  "pandas>=2.0,<4.0",
  "scipy>=1.10,<2.0",
  "matplotlib>=3.7,<4.0",
  "tqdm>=4.64,<5.0",
  "psutil>=5.9,<8.0",
  "easyocr>=1.7,<2.0",
  "ultralytics>=8.0,<9.0",
]


keywords = [
  "plant-phenotyping",
  "fruit-morphology",
  "plant-breeding"
]

classifiers = [
  "Development Status :: 4 - Beta",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Image Processing",
]

[project.optional-dependencies]
pdf = ["PyMuPDF>=1.23,<2.0"]
all = ["PyMuPDF>=1.23,<2.0", "shiny>=1.0,<2.0"]

dev = ["pytest", "pytest-cov"]

[project.scripts]
traitly = "traitly.cli:main"
traitly-app = "traitly.shiny_app.app:run"

[project.urls]
Repository = "https://github.com/mariameraz/traitly"
Documentation = "https://traitly.readthedocs.io/en/latest/"
Issues = "https://github.com/mariameraz/traitly/issues"
Changelog = "https://github.com/mariameraz/traitly/blob/main/CHANGELOG.md"

[tool.hatch.build.targets.wheel]
packages = ["src/traitly"]

[tool.hatch.build]
include = [
  "src/traitly/**",
  "README.md",
  "LICENSE*"
]
