# tests/test_internal_fruit_phenotyping.py

####################
# Standard library #
####################
import shutil

#########################
# Third-party libraries #
#########################
from pathlib import Path
import pandas as pd
import pytest

####################
# Internal library #
####################
from traitly.fruit_phenotyping import FruitInternalAnalyzer


##############################################################################
# Fixtures
##############################################################################

@pytest.fixture(autouse=True)
def clean_results():
    """Remove all result directories after each test to avoid cross-test contamination."""
    yield
    for folder in [
        "tests/sample_data/Results",
        "tests/sample_data/Image_Results",
        "tests/sample_data/Stamp_Results",
    ]:
        shutil.rmtree(folder, ignore_errors=True)


##############################################################################
# analyze_folder
##############################################################################

def test_analyze_folder_creates_outputs():
    """
    Folder with 3 example images.
    2 images have QR codes, 1 image does not have a QR code.
    Results are saved by default inside sample_data/Results.
    img_test_4.jpg does not contain valid locules —
    the function should not stop but report the error.
    """
    sample_data = Path("tests/sample_data")

    analyzer = FruitInternalAnalyzer(sample_data)
    analyzer.analyze_folder(analyze_morphology=False)

    results_dir = sample_data / "Results"

    # 1) Output directory was created
    assert results_dir.is_dir()

    # 2) color_results.csv exists and has at least one row
    color_results = results_dir / "color_results.csv"
    assert color_results.exists()
    df = pd.read_csv(color_results)
    assert len(df) > 0

    # 3) session_report.txt exists (generated by analyze_folder)
    assert (results_dir / "session_report.txt").exists()


def test_analyze_folder_raises_if_not_directory():
    """Passing a single image path instead of a directory should raise ValueError."""
    example_img = "tests/sample_data/img_test_3.jpg"
    analyzer = FruitInternalAnalyzer(str(example_img))

    with pytest.raises(ValueError, match="not a single file"):
        analyzer.analyze_folder()


def test_analyze_folder_error_report_created_when_invalid_image():
    """
    When the folder contains an image that fails processing,
    error_report.txt should be created.
    """
    sample_data = Path("tests/sample_data")

    analyzer = FruitInternalAnalyzer(sample_data)
    analyzer.analyze_folder(analyze_morphology=True)

    results_dir = sample_data / "Results"
    error_report = results_dir / "error_report.txt"
    assert error_report.exists()


##############################################################################
# Single image — with QR and label
##############################################################################

def test_analyze_image_creates_outputs():
    """
    Single image with QR code present.
    Results are saved in Image_Results folder.
    Note: session_report.txt is only generated by analyze_folder(), not save_all().
    """
    sample_data = "tests/sample_data/img_test_1.jpg"

    analyzer = FruitInternalAnalyzer(sample_data)
    analyzer.load_image(plot = False)
    analyzer.setup_measurements()
    analyzer.generate_fruit_mask(plot = False)
    analyzer.detect_fruits()
    analyzer.analyze_morphology(plot=False)
    analyzer.analyze_color(plot=False)
    analyzer.results.save_all(output_dir="tests/sample_data/Image_Results")

    results_dir = Path("tests/sample_data/Image_Results")

    # 1) Annotated image exists
    assert (results_dir / "img_test_1_annotated.jpg").exists()

    # 2) Morphology CSV exists and has at least one row
    morpho_results = results_dir / "img_test_1_morphology_results.csv"
    assert morpho_results.exists()
    morpho_df = pd.read_csv(morpho_results)
    assert len(morpho_df) > 0

    # 3) Color CSV exists and has at least one row
    color_results = results_dir / "img_test_1_color_results.csv"
    assert color_results.exists()
    color_df = pd.read_csv(color_results)
    assert len(color_df) > 0


def test_analyze_image_result_columns():
    """Morphology results should contain the expected columns."""
    sample_data = "tests/sample_data/img_test_1.jpg"

    analyzer = FruitInternalAnalyzer(sample_data)
    analyzer.load_image(plot = False)
    analyzer.setup_measurements()
    analyzer.generate_fruit_mask(plot = False)
    analyzer.detect_fruits()
    analyzer.analyze_morphology(plot=False)
    analyzer.results.save_all(output_dir="tests/sample_data/Image_Results")

    morpho_results = Path("tests/sample_data/Image_Results/img_test_1_morphology_results.csv")
    df = pd.read_csv(morpho_results)

    # Column names confirmed from actual output
    expected_columns = ["image_name", "fruit_id"]
    for col in expected_columns:
        assert col in df.columns, f"Missing expected column: '{col}'"


##############################################################################
# Single image — without QR
##############################################################################

def test_analyze_image_with_no_qr():
    """
    Image without a QR code.
    Label detection is enabled but no QR is present —
    the label column should contain a fallback string.
    """
    sample_data = "tests/sample_data/img_test_5.jpg"

    analyzer = FruitInternalAnalyzer(sample_data)
    analyzer.load_image(plot = False)
    analyzer.setup_measurements(detect_label=True)
    analyzer.generate_fruit_mask(plot = False)
    analyzer.detect_fruits()
    analyzer.analyze_morphology(plot=False)
    analyzer.analyze_color(plot=False)
    analyzer.results.save_all(output_dir="tests/sample_data/Image_Results")

    results_dir = Path("tests/sample_data/Image_Results")

    # 1) Annotated image exists
    assert (results_dir / "img_test_5_annotated.jpg").exists()

    # 2) Morphology CSV exists and has at least one row
    morpho_results = results_dir / "img_test_5_morphology_results.csv"
    assert morpho_results.exists()
    morpho_df = pd.read_csv(morpho_results)
    assert len(morpho_df) > 0

    # 3) Color CSV exists and has at least one row
    color_results = results_dir / "img_test_5_color_results.csv"
    assert color_results.exists()
    color_df = pd.read_csv(color_results)
    assert len(color_df) > 0


##############################################################################
# Single image — stamps (whole fruit, no slices)
##############################################################################

def test_analyze_image_with_stamps():
    """
    Image with whole fruits (stamps) instead of cross-sections,
    without QR code and without label detection.
    """
    sample_data = "tests/sample_data/stamp/img_test_4.jpg"

    analyzer = FruitInternalAnalyzer(sample_data)
    analyzer.load_image(plot = False)
    analyzer.setup_measurements(detect_label=False)
    analyzer.generate_fruit_mask(plot = False, stamp=True)
    analyzer.detect_fruits()
    analyzer.analyze_morphology(plot=False)
    analyzer.results.save_all(output_dir="tests/sample_data/Stamp_Results")

    results_dir = Path("tests/sample_data/Stamp_Results")

    # 1) Annotated image exists
    assert (results_dir / "img_test_4_annotated.jpg").exists()

    # 2) Morphology CSV exists and has at least one row
    results = results_dir / "img_test_4_morphology_results.csv"
    assert results.exists()
    df = pd.read_csv(results)
    assert len(df) > 0


##############################################################################
# Edge cases
##############################################################################

def test_analyze_image_fruit_count():
    """The number of detected fruits should be greater than zero."""
    sample_data = "tests/sample_data/img_test_1.jpg"

    analyzer = FruitInternalAnalyzer(sample_data)
    analyzer.load_image(plot = False)
    analyzer.setup_measurements()
    analyzer.generate_fruit_mask(plot = False)
    analyzer.detect_fruits()

    assert len(analyzer.fruit_locule_map) > 0


def test_analyze_image_with_scale_reference_returns_cm_units():
    """
    When a scale reference is detected, px_per_cm should be a positive float
    and results should be reported in cm units.
    """
    sample_data = "tests/sample_data/img_test_1.jpg"

    analyzer = FruitInternalAnalyzer(sample_data)
    analyzer.load_image(plot = False)
    analyzer.setup_measurements()

    assert analyzer.px_per_cm is not None
    assert analyzer.px_per_cm > 0


def test_analyze_stamp_no_scale_returns_px_units():
    """
    Stamp image without size reference — px_per_cm should be None
    and results should be in pixel units.
    """
    sample_data = "tests/sample_data/stamp/img_test_4.jpg"

    analyzer = FruitInternalAnalyzer(sample_data)
    analyzer.load_image(plot = False)
    analyzer.setup_measurements(detect_label=False)

    assert analyzer.px_per_cm is None


def test_results_not_available_before_analysis():
    """Accessing results before running analyze_morphology should return None."""
    sample_data = "tests/sample_data/img_test_1.jpg"

    analyzer = FruitInternalAnalyzer(sample_data)
    analyzer.load_image(plot = False)

    assert analyzer.results is None